GET http://localhost:5000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJFZHdhcmQgQnJpdG8iLCJlbWFpbHMiOiJlZHdhcmRAaG90bWFpbC5jb20iLCJpYXQiOjE2NzEyMDE4NTcsImV4cCI6MTY3MTIwNTQ1N30.bnP5XuWhVxBda-BUNT4RBPGiRh1Hqp_3i81-4dwf-bw


###
POST  http://localhost:5000/register
Content-Type: application/json

{
    "name":"Edward Brito",
    "email":"edward@hotmail.com",
    "password":"12345",
    "confPassword":"12345"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{   
    "email":"edward@hotmail.com",
    "password":"edward11",
}
