GET http://localhost:5000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsIm5hbWUiOiJFZHdhcmQgQnJpdG8iLCJlbWFpbHMiOiJtYW51ZWxAaG90bWFpbC5jb20iLCJpYXQiOjE2NzEyMDM4NTUsImV4cCI6MTY3MTIwNzQ1NX0.XQouIjQNwmky8zpwMgdI09Pcpa5qWyU9TffLoL66JOI

###
POST  http://localhost:5000/register
Content-Type: application/json

{
    "name":"Edward Brito",
    "email":"manuel@hotmail.com",
    "password":"12345",
    "confPassword":"12345"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{   
    "email":"edward@hotmail.com",
    "password":"edward11",
}

###
GET http://localhost:5000/token

###
DELETE  http://localhost:5000/logout

